GET http://localhost:6000/classes 

##################

POST http://localhost:6000/classes HTTP/1.1
content-type: application/json

{
    "class":{
        "section": "5^C",
        "teachers": [
             "649f0cc2d576e78d118769c8",
             "64a464964d0d1061edb4ac33"
        ],
        "students": [
            "649f0cc9d576e78d118769cb"
        ]
    } 
}