GET http://localhost:5050/class 

##################

GET http://localhost:5050/class/64ac76f28d3f7c7ba07f10fb


###################

POST http://localhost:5050/class HTTP/1.1
content-type: application/json

{
    "class":{
        "section": "5^B",
        "students": [
         "64b2662d1122c31fc0397c6e"
        ]
    } 
}