GET http://localhost:5050/teacher

########################################

GET http://localhost:5050/teacher/64ad2dcb693a3d9ca70a67b5

########################################

POST http://localhost:5050/teacher HTTP/1.1
content-type: application/json

{
    "name": "Salvatore",
    "surname": "Messana",
    "birth_date": "4/05/1943",
    "email": "salvo87messana@gmail.com",
    "password": "luna2",
    "fiscal_code": "sssssssssssssss",
    "school_subject": "matematica",
    "role": "teacher",
    "class_group": {
        "classes": [
            "64ac76f28d3f7c7ba07f10fb"
        ]
    }
    
}

#############################
PATCH http://localhost:5050/teacher/64ad2dcb693a3d9ca70a67b5 HTTP/1.1
content-type: application/json

{
    "class_group": {
        "classes": [
            "64b3bc262c5493bbdaf4d89a",
            "64b2682c1122c31fc0397c9e"
        ]
    }
}