GET http://localhost:6000/teachers

########################################

POST http://localhost:6000/teachers HTTP/1.1
content-type: application/json

{
    "name": "Salvatore",
    "surname": "Messana",
    "birth_date": "4/05/1943",
    "email": "salvatore90messana@gmail.com",
    "password": "briciola2",
    "fiscal_code": "MSSNDR90D12E80VT",
    "school_subject": "storia",
    "class": "5^A"
}