GET http://localhost:5050/teacher

########################################

POST http://localhost:5050/teacher HTTP/1.1
content-type: application/json

{
    "name": "Carlo",
    "surname": "Leone",
    "birth_date": "21/04/1987",
    "email": "carlo87leone@gmail.com",
    "password": "luna2",
    "fiscal_code": "ccccccccccccccccc",
    "school_subject": "fisica",
    "role": "teacher",
    "class_group": {
        "classes": [
            "64a82007edebac3516a6e6b7"
        ]
    }
    
}